name: 2d
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=24.2
  - numpy=1.23.5
  - matplotlib=3.7.2
  - pytorch=2.1.1
  - torchvision=0.16.1
  - torchaudio=2.1.1
  - cudatoolkit=11.8
  - pyyaml=6.0.1
  - tqdm=4.66.5
  - tensorboard=2.14.0
  - pip:
    - torchsde==0.2.6
    - einops==0.8.0
    - wandb==0.17.9
    - scikit-learn==1.3.2
    - scipy==1.10.1 